const { API_KEY, handleCorsAndLimit } = require('./_shared');

export default async function handler(req, res) {
    if (handleCorsAndLimit(req, res, 'image')) return;

    try {
        const { prompt } = req.body;
        if (!prompt || prompt.length > 1000) {
            return res.status(400).json({ success: false, error: "Valid prompt up to 1000 characters is required." });
        }

        // Using Google AI Studio's Imagen 3 REST API endpoint
        const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/imagen-3.0-generate-001:predict?key=${API_KEY}`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                instances: [{ prompt: prompt }],
                parameters: { sampleCount: 1 }
            })
        });

        const data = await response.json();
        
        if (data.error) throw new Error(data.error.message);
        
        const base64 = data.predictions?.[0]?.bytesBase64Encoded;
        if (!base64) throw new Error("No image generated by Google Imagen.");

        res.status(200).json({
            success: true,
            image: `data:image/png;base64,${base64}`
        });
    } catch (error) {
        res.status(500).json({ success: false, error: "Image Generation Failed", message: error.message });
    }
}
